### ISSUE TITLE
Vehicles not checking to move forward

### ISSUE THREAD

**Issue by ben-dodd-dev** [mitgobla/Traffic-Improvement#2]
A vehicle may move forward once into an empty space or if the car in front has successfully moved. However, some vehicles remain stuck for the entire simulation period after running once.

**Comment by Edward-Upton** [comment]
Redesign of how vehicles look at the vehicle in front. Each vehicle has a "moved" event variable that gets updated when they leave the queue or move up the queue. The vehicle behind sees this change and then runs the functions necessary.
