### ISSUE TITLE
No vehicle or personality randomness

### ISSUE THREAD

**Issue by Edward-Upton** [mitgobla/Traffic-Improvement#4]
Currently there is no randomness other than when vehicles get added. Possible additions:
- Driver acceleration, speed and delay randomness.
- Vehilce size, type, speed, acceleration randomness.
This would more accurately replicate a traffic environment.

**Comment by ben-dodd-dev** [comment]
I will look into other government road statistics and data to understand the different relationships between human and traffic factors that affect a traffic environment, because I don't think we looked into that deep enough.
